akesatu             = float(input("a \t : "))
bkedua              = float(input("b \t : "))
iketiga             = float(input("i \t : "))
jkeempat            = float(input("j \t : "))
xkelima             = float(input("x \t : "))
ykeenam             = float(input("y \t : "))
has = (akesatu-bkedua)*(iketiga/jkeempat)-(xkelima+ykeenam)
print("Hasil = {:.3f} " .format(round(has)))